cats-site-w4d2/cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests
  patch 'cat_rental_requests', to: 'cat_rental_requests#approve'
  patch 'cat_rental_requests', to: 'cat_rental_requests#deny'
end

cats-site-w4d2/cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats-site-w4d2/cats/app/models/cat.rb
class Cat < ApplicationRecord
  COLORS = ['black', 'yellow', 'gray', 'golden', 'flaming', 'purple']
  validates :color, presence: true, inclusion: { in: COLORS }
  validates :birth_date, presence: true
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: ['M', 'F']}
  validates :description, presence: true

  def age
    ((Date.today - self.birth_date) / 365).floor
  end

  has_many :rental_requests,
  class_name: 'CatRentalRequest',
  foreign_key: :cat_id,
  primary_key: :id,
  dependent: :destroy

end

cats-site-w4d2/cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: { in: ['pending', 'approved', 'denied']}
  validate :does_not_overlap_approved_request

  belongs_to :cat,
  class_name: 'Cat',
  foreign_key: :cat_id,
  primary_key: :id

  def overlapping_requests
    CatRentalRequest
    .where(cat_id: self.cat_id)
    .where.not(id: self.id)
    .where.not("start_date > :end_date OR end_date < :start_date", start_date: self.start_date, end_date: self.end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'approved')
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'pending')
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists? && self.status != 'denied'
      errors[:cat_request] << ['invalid request']
    end
  end

  def approve!
    if self.status == 'pending'
      CatRentalRequest.transaction do
        self.update(status: 'approved')
        self.overlapping_pending_requests.each do |request|
          request.deny!
        end
      end
    end
  end

  def deny!
    self.update(status: 'denied')
  end

end

cats-site-w4d2/cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

cats-site-w4d2/cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_params)
    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      render :new
    end
  end

private

  def cat_rental_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id, :status)
  end

end

cats-site-w4d2/cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :show
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  def cat_params
    params.require(:cat).permit(:birth_date, :sex, :name, :color, :description)
  end
end

cats-site-w4d2/cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats-site-w4d2/cats/app/views/cats/_form.html.erb
<form class="" action="<%= cat.persisted? ? cat_url(cat) : cats_url %>" method="post">
  <% if cat.persisted?%>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="">Name:
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <p></p>
  <label for="">Sex:
    <input type="radio" name="cat[sex]" id="Male" value="M" <%= cat.sex == 'M' ? 'checked' : "" %>>
    <label for="Male">Male</label>
    <input type="radio" name="cat[sex]" id="Female" value="F" <%= cat.sex == 'F' ? 'checked' : "" %>>
    <label for="Female">Female</label>
  </label>
  <p></p>
  <label for="">Color:
    <select class="" name="cat[color]">
      <option disabled selected>Select Color:</option>
      <option value='black' <%= cat.color == 'black' ? 'selected' : "" %>>Black</option>
      <option value='yellow' <%= cat.color == 'yellow' ? 'selected' : "" %>>Yellow</option>
      <option value='gray' <%= cat.color == 'gray' ? 'selected' : "" %>>Gray</option>
      <option value='golden' <%= cat.color == 'golden' ? 'selected' : "" %>>Golden</option>
      <option value='flaming' <%= cat.color == 'flaming' ? 'selected' : "" %>>Flaming</option>
      <option value='purple' <%= cat.color == 'purple' ? 'selected' : "" %>>Purple</option>
    </select>
  </label>
  <p></p>
  <label for="">Birthdate:</label>
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <p><label for="">Description:
    <br><br>
    <textarea name="cat[description]" rows="8" cols="80"><%= cat.description %></textarea>
  </label></p>
  <p>
  <input type="submit" value="<%= cat.persisted? ? "Edit cat" : "Add Cat"%>"></p>


</form>

cats-site-w4d2/cats/app/views/cats/edit.html.erb
<h1>Edit a Cat!!</h1>

<%= render 'form', cat: @cat %>

cats-site-w4d2/cats/app/views/cats/index.html.erb
<h1> All the cats! </h1>

<% @cats.each do |cat| %>
<a href="<%= cat_url(cat) %>"><%= cat.name %></a><br>
<% end %>

cats-site-w4d2/cats/app/views/cats/new.html.erb
<h1>Add a Cat!!</h1>

<%= render 'form', cat: @cat %>

cats-site-w4d2/cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <td>
      Name:
    </td>
    <td>
      <%= @cat.name %>
    </td>
  </tr>

  <tr>
    <td>
      Age:
    </td>
    <td>
      <%= @cat.age %>
    </td>
  </tr>

  <tr>
    <td>
      Color:
    </td>
    <td>
      <%= @cat.color %>
    </td>
  </tr>

  <tr>
    <td>
      Sex:
    </td>
    <td>
      <%= @cat.sex %>
    </td>
  </tr>

  <tr>
    <td>
      Description:
    </td>
    <td>
      <%= @cat.description %>
    </td>
  </tr>
</table>
<br><br>

<h2>Rental Requests</h2>
<table border = "1" cellpadding="10">
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order(:start_date).each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.status %></td>
    <td><input type="submit" value="Accept"></td>
    <td><input type="submit" value="Deny"></td>
  </tr>
  <% end %>
</table>

cats-site-w4d2/cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>